[package]
name = "xtask"
version = "0.3.0"
authors = [
  "Wink Saville <wink@saville.com",
  "Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
